# -*- coding: utf-8 -*-
"""MLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4cLfig5WWEWNGd4wnTKanVQHtonJTsD

# Movie Recommendation system
"""

import numpy as np
import pandas as pd

# Importing the datasets
moviesData = pd.read_csv('/content/tmdb_5000_movies.csv')
creditsData = pd.read_csv('/content/tmdb_5000_credits.csv')
moviesData.head(1)

# Merging the dataset based on the title.
moviesData = moviesData.merge(credits,on = "title")
moviesData.head(1)

moviesData.head(1)

# Using the only columns which are required for our predictions
# genres
# id
# keywords
# title
# overview
# cast
# crew

moviesData = moviesData[['movie_id','title','genres','keywords','overview','cast','crew']]

moviesData.head(1)

import ast

def convert(text):
  L = []
  for i in ast.literal_eval(text):
    L.append(i['name'])
  return L

moviesData.dropna(inplace = True)

moviesData['genres'] = moviesData['genres'].apply(convert)

moviesData.head(1)

moviesData['keywords'] = moviesData['keywords'].apply(convert)
moviesData.head(1)

# cast Convert
def cast_convert(text):
  L = []
  counter = 0
  for i in ast.literal_eval(text):
    if counter < 3:
      L.append(i['name'])
    counter += 1
  return L

moviesData['cast'] = moviesData['cast'].apply(cast_convert)
moviesData.head(1)

moviesData['cast'] = moviesData['cast'].apply(lambda x:x[0:3])

# fetch director
def fectch_director(text):
  L = []
  for i in ast.literal_eval(text):
    if i['job'] == 'Director':
      L.append(i['name'])
  return L

moviesData['crew'] = moviesData['crew'].apply(fectch_director)

moviesData.head(1)

moviesData['overview'] = moviesData['overview'].apply(lambda x:x.split())
moviesData.sample(5)

# function to remove the spaces to prevent confusion for the model

def remove_space(L):
  l1 = []
  for i in L:
    l1.append(i.replace(" ",""))
  return l1

moviesData['cast'] = moviesData['cast'].apply(remove_space)
moviesData['crew'] = moviesData['crew'].apply(remove_space)
moviesData['genres'] = moviesData['genres'].apply(remove_space)
moviesData['keywords'] = moviesData['keywords'].apply(remove_space)

moviesData.head(1)

moviesData['tags'] = moviesData['overview'] + moviesData['genres'] + moviesData['keywords'] + moviesData['cast'] + moviesData['crew']

new_df = moviesData[['movie_id','title','tags']]

new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

new_df.head(1)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vector = cv.fit_transform(new_df['tags']).toarray()

vector.shape

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vector)

new_df[new_df['title'] == 'The Lego Movie'].index[0]

# Function to Recommend movies

def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

recommend('Titanic')

import pickle

pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

pickle.dump(similarity,open('similarity.pkl','wb'))